Membuat Matriks dengan Numpy

In [1]:
import numpy as np

In [7]:
matrix_2x2 = np.matrix([[1,2],[3,4]])
print(matrix_2x2)

[[1 2]
 [3 4]]


In [5]:
matrix_2x3 = np.matrix('1 2; 3 4; 5 6')
print(matrix_2x3)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
print(np.zeros([3, 2]))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
print(np.ones([2, 3]))

[[1. 1. 1.]
 [1. 1. 1.]]
