Creating Numpy Arrays

In [1]:
daftar = [1, 2 , 3]

In [2]:
print(daftar)

[1, 2, 3]


In [3]:
import numpy as np

In [4]:
numpy_1 = np.array(daftar)

In [5]:
print(numpy_1)

[1 2 3]


In [6]:
zeros_array = np.zeros(6)
print(zeros_numpy)

NameError: name 'zeros_numpy' is not defined

In [7]:
zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [8]:
ones_array = np.ones(11)

In [9]:
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
range_array = np.arange(12)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
range_array_1 = np.arrange(5,12)
print(range_array_1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [12]:
range_array_1 = np.arange(5,12)
print(range_array_1)

[ 5  6  7  8  9 10 11]


In [13]:
range_array_2 = np.arange(0,20,2)
print(range_array_2)

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
linspace_array = np.linspace[0, 12, 5]
print(linspace_array)

TypeError: 'function' object is not subscriptable

In [15]:
linspace_array = np.linspace(0, 12, 5)
print(linspace_array)

[ 0.  3.  6.  9. 12.]


In [16]:
linspace_array_1 = np.linspace(2, 25, 10)
print(linspace_array_1)

[ 2.          4.55555556  7.11111111  9.66666667 12.22222222 14.77777778
 17.33333333 19.88888889 22.44444444 25.        ]


In [17]:
linspace_array_2 = np.linspace(2, 25)
print(linspace_array_2)

[ 2.          2.46938776  2.93877551  3.40816327  3.87755102  4.34693878
  4.81632653  5.28571429  5.75510204  6.2244898   6.69387755  7.16326531
  7.63265306  8.10204082  8.57142857  9.04081633  9.51020408  9.97959184
 10.44897959 10.91836735 11.3877551  11.85714286 12.32653061 12.79591837
 13.26530612 13.73469388 14.20408163 14.67346939 15.14285714 15.6122449
 16.08163265 16.55102041 17.02040816 17.48979592 17.95918367 18.42857143
 18.89795918 19.36734694 19.83673469 20.30612245 20.7755102  21.24489796
 21.71428571 22.18367347 22.65306122 23.12244898 23.59183673 24.06122449
 24.53061224 25.        ]
