Operasi untuk memodifikasi elemen array

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0, 7)
print(an_array)

[0 1 2 3 4 5 6]


In [3]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5  6]


In [5]:
an_array = np.arange(0, 7)
print(np.append(an_array, [7, 8]))

[0 1 2 3 4 5 6 7 8]


In [8]:
print(np.insert(an_array, 5, [13, 14]))

[ 0  1  2  3  4 13 14  5  6]


In [11]:
print(np.delete(an_array, 4))

[0 1 2 3 5 6]


In [12]:
print(an_array * 2)

[ 0  2  4  6  8 10 12]


In [14]:
print(an_array - 2)

[-2 -1  0  1  2  3  4]


In [15]:
array_baru = np.array([3, 6, 7, 21, 9, 11, 13])
print(np.sort(array_baru))

[ 3  6  7  9 11 13 21]


In [19]:
print(-np.sort(-array_baru))

[21 13 11  9  7  6  3]
