Penggunaan Numpy untuk Mengolah Nilai Rapot

In [1]:
import numpy as np

In [2]:
nilai_siswa = np.array([56, 78, 98, 90, 58, 64, 67, 72, 93, 51])
print(nilai_siswa)

[56 78 98 90 58 64 67 72 93 51]


In [3]:
rata2_kelas = np.average(nilai_siswa)
print(rata2_kelas)

72.7


In [4]:
nilai_tertinggi = np.amax(nilai_siswa)
print(nilai_tertinggi)

nilai_terendah = np.amin(nilai_siswa)
print(nilai_terendah)

98
51


In [5]:
print(np.argmax(nilai_siswa))
print(np.argmin(nilai_siswa))

2
9


In [6]:
print(np.sort(nilai_siswa))
print(-np.sort(-nilai_siswa))

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [7]:
tambah_nilai = nilai_siswa * 1.1
print(tambah_nilai)

[ 61.6  85.8 107.8  99.   63.8  70.4  73.7  79.2 102.3  56.1]


In [8]:
tambah_nilai = nilai_siswa + 10
print(tambah_nilai)

[ 66  88 108 100  68  74  77  82 103  61]


In [9]:
print(np.add(nilai_siswa, np.ones(10)))

[57. 79. 99. 91. 59. 65. 68. 73. 94. 52.]


In [10]:
print(np.add(nilai_siswa, np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])))

[ 57  80 101  94  63  70  74  80 102  61]


In [11]:
print(np.add(nilai_siswa, np.ones(7)))

ValueError: operands could not be broadcast together with shapes (10,) (7,) 